### ISSUE TITLE
Route Monitor Installation Guide - missing

### ISSUE THREAD

**Issue by ikatinas** [Esri/route-monitor-for-geoevent#5]
In the installation instructions Step 2, it says:
"Follow the *Route Monitor Installation Guide* (**downloadable from Gallery**) to set up the server components of the Route Monitor."
But *"Route Monitor Installation Guide"* is **not available** from the ESRI gallery anymore, at least not publicly. Could it be included among the source files in github? Or at least include a link in the *readme* file.

**Comment by mzesri** [comment]
The Route Monitor application is not actively maintained by the GeoEvent team.  The code here will not work with the latest version of the GeoEvent Extension and the Operaton Dashboard.  The tutorials and sample data which were on the Gallery has been removed.  If you are interested in how it used to work, you can contact me individually for the matching materials.

**Comment by arepsher** [comment]
So, after all of the planning for the use of these tools, Esri is just going to eliminate them? How many times have we seen them used on stage to promote GEP, wowing the masses?
It sucks that we have to pay for seats for AGOL or Portal so that we can use the dashboard, etc... But then to have features just dissolve?
Uncool.

Sorry. It has been awhile since I have been negative here....



-----Original Message-----

**Comment by mzesri** [comment]
Yes, Route Monitor was a good tool to demonstrate the integration of GEP, Webmap, Mobile SDK and the dashboard.  It also has many examples of how to extend the GEP with the SDK.  However, it was not a product.  Even though the GeoEvent team is not working on it, the Professional Services is actively using it for projects.  You can contact them for project needs.
